# Generated by Django 2.2.2 on 2019-07-26 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datamodel', '0046_auto_20190716_1513'),
        ('datamodel', '0035_auto_20190416_1339'),
    ]

    operations = [
    ]
