# Generated by Django 2.2.2 on 2019-10-29 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamodel', '0047_merge_20190726_0901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gebruiksrechten',
            name='informatieobject',
            field=models.URLField(help_text='URL-referentie naar het INFORMATIEOBJECT.'),
        ),
    ]
