version: '3.4'

services:
  db:
    volumes:
      - postgres_data:/var/lib/postgresql/data
  web:
    volumes:
      - private_media:/app/private-media
  nginx:
    volumes:
      - private_media:/private-media
      - nginx_logs:/var/log/nginx

volumes:
  postgres_data:
  private_media:
  nginx_logs:
