# Inspired by https://docs.docker.com/compose/django/
version: '3.4'

services:
  db:
    image: postgres:10
    # environment:
    #   - POSTGRES_USER=${PG_USER:drc}
    #   - POSTGRES_PASSWORD=${PG_PASSWORD:drc}
  web:
    build: .
    environment:
      - DJANGO_SETTINGS_MODULE=drc.conf.docker
      - SECRET_KEY=${SECRET_KEY}
    depends_on:
      - db

  nginx:
    image: nginx:1.15
    ports:
      - 8000:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
