# Generated by Django 2.0.13 on 2019-05-15 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='djangostorage',
            name='enkelvoudiginformatieobject',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='djangostorage', to='datamodel.EnkelvoudigInformatieObject'),
        ),
    ]
